# permissions for end users to view scheduledautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduledautoscaler-viewer-role
rules:
- apiGroups:
  - microservice.microservice.example.com
  resources:
  - scheduledautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microservice.microservice.example.com
  resources:
  - scheduledautoscalers/status
  verbs:
  - get
