apiVersion: microservice.microservice.example.com/v1beta1
kind: Microservice
metadata:
  name: deployment-sample
spec:
  replicas: 3
  labels:
    asd: asda
  image: nginx:latest
  podAnnotations:
    pod: "anno"
  ingress:
    - containerPort: 8090
      host: 
      - asd.dsa.asd
      paths:
        - /dsaa
        - /as
        - /fds
      name: test3
    - containerPort: 443
      host: 
      - fff.flkgklh.eirt
      paths:
        - /dsagkfd
        - /asopgkdf
        - /fdslkgfgkglkf
      name: test2
    - containerPort: 3945
      host: 
      - nmmm.mmm.mmm
      paths:
        - /dsaa
        - /asfds
        - /fdsasd
      name: test1
